(()=>{var i=class{constructor(e){this.musics=e.musics,this.musics_list=Object.keys(this.musics),this.targetAudio=null,this.SetTargetAudio("audio"),this.targetMenu=e.targetMenu,this.targetMusicImg=e.targetMusicImg,this.targetMusicName=e.targetMusicName,this.targetMusicArtist=e.targetMusicArtist,this.selectedMusic=null,this.onMusicChanged=e.onMusicChanged||null,this.onInitialized=e.onInit||null,this.onMusicPaused=e.onMusicPaused||null,this.onMusicPlayed=e.onMusicPlayed||null,this.playpausebtn=null,this.RandomlySelectMusic(),this.setView(),this.loadMusics_in_menu()}loadMusics_in_menu(){for(let e in this.musics){let t=`
                <div class="menu-music" data-light-search="${e}">
                    <img src="music-images/${e}.jpg" class="menu-music-img">
                    <div class="menu-music-name_artist">
                        <h1>${e}</h1>
                        <h2>${this.musics[e]}</h2>
                    </div>
                    <div class="play-pause-container blob-6" data-target-music="${e}">
                        <img src="icons/play-button-24.png" class="play-pause blob-6">
                    </div>
                </div>
            `;this.targetMenu.innerHTML+=t}document.querySelector(`[data-light-search="${this.selectedMusic}"]`).classList.add("selected"),document.querySelectorAll("div[data-target-music]").forEach(e=>{e.addEventListener("click",t=>{if(e.getAttribute("data-target-music")==this.selectedMusic)document.querySelector(".play-pause-btn").click();else{this.selectedMusic=e.getAttribute("data-target-music"),document.querySelector(".music-controlers").innerHTML=null;let s=document.createElement("audio");s.setAttribute("id","audio"),document.querySelector(".music-controlers").appendChild(s),this.SetTargetAudio("audio"),this.setView(),(this.onMusicChanged||(()=>{}))(e)}})})}setView(){this.targetMusicImg.setAttribute("src","music-images/"+this.selectedMusic+".jpg"),this.targetMusicName.innerText=this.selectedMusic,this.targetMusicArtist.innerText=this.musics[this.selectedMusic],this.targetAudio.innerHTML=null,this.targetAudio.appendChild(this.makeSourceElement({tyep:"audio/mpeg",src:"musics/"+this.selectedMusic+".mp3"})),this.initGreenAudio(),(this.onInitialized||(()=>{}))()}initGreenAudio(){new GreenAudioPlayer(".music-controlers",{showDownloadButton:!0}),this.SetTargetAudio("audio"),this.init_OnPause_OnPlay()}makeSourceElement(e){let t=document.createElement("source");for(let s in e)t.setAttribute(s,e[s]);return t}RandomlySelectMusic(){this.selectedMusic=this.musics_list[this.randomInt(0,this.count)]}randomInt(e,t){return Math.floor(Math.random()*(t-e)+e)}init_OnPause_OnPlay(){this.playpausebtn=document.querySelector(".play-pause-btn"),this.playpausebtn.addEventListener("click",()=>{this.playpausebtn.getAttribute("aria-label")=="Play"?(this.onMusicPaused||(()=>{}))():(this.onMusicPlayed||(()=>{}))()})}get count(){return this.length?this.length:(this.length=this.musics_list.length,this.length)}SetTargetAudio(e){this.targetAudio=document.getElementById(e)}};(async()=>{let n=null,e=document.getElementById("audio"),t=`
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 18 24">
        <path fill="#fff" fill-rule="evenodd" d="M18 12L0 24V0" class="play-pause-btn__icon"></path>
    </svg>`,s=`
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 18 24">
        <path fill="#fff" fill-rule="evenodd" d="M0 0h6v24H0zM12 0h6v24h-6z" class="play-pause-btn__icon"></path>
    </svg>`,u=new i({musics:await(await fetch("musics.json")).json(),targetAudio:document.getElementById("audio"),targetMenu:document.getElementById("musics-list"),targetMusicImg:document.getElementById("selected-music-img"),targetMusicName:document.getElementById("selected-music-name"),targetMusicArtist:document.getElementById("selected-music-artist"),onInit:()=>{},onMusicChanged:()=>{document.querySelector(".menu-music.selected .play-pause-container").innerHTML=t,document.querySelector(".selected").classList.remove("selected"),document.querySelector(`[data-light-search="${u.selectedMusic}"]`).classList.add("selected"),document.querySelector(".play-pause-btn").click()},onMusicPlayed:()=>{document.querySelector(".menu-music.selected .play-pause-container").innerHTML=s},onMusicPaused:()=>{document.querySelector(".menu-music.selected .play-pause-container").innerHTML=t}}),l=document.querySelector(".musical-icon"),r=document.getElementById("music-container"),c=document.getElementById("menu-column"),m=document.getElementById("music-column"),a=document.getElementById("close-menu");l.addEventListener("click",()=>{c.classList.replace("hidden-menu","show-menu")}),a.addEventListener("click",()=>{c.classList.replace("show-menu","hidden-menu")});let o=document.getElementById("search-music"),d=document.querySelectorAll(".menu-music");lightSearch(o,d,{display:"flex"})})();})();
